# Generated by Django 3.1.2 on 2021-05-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0005_auto_20210524_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='datetime',
            new_name='datetimeC',
        ),
    ]
