# Generated by Django 3.1.2 on 2021-05-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0006_auto_20210524_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Vehicle',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='vehicle',
        ),
    ]
