# Generated by Django 3.1.2 on 2021-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0007_auto_20210524_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='frequency',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_operation',
            field=models.CharField(default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='employee',
            name='longtitude',
            field=models.CharField(max_length=100),
        ),
    ]
