# Generated by Django 3.1.2 on 2021-05-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0008_auto_20210525_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Operation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='vehicle',
            new_name='operation',
        ),
    ]
