# Generated by Django 3.1.2 on 2021-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0009_auto_20210525_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='frequency',
            field=models.CharField(default=0, max_length=223),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_operation',
            field=models.CharField(default=0, max_length=223),
        ),
    ]
